version: '3.8'
services:

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop_database

  web:
    build: ../app/
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    restart: always
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 8000:8000


volumes:
  static_value:
  postgres_data:
