version: '3.8'
services:

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/shop_admin/
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  web:
    build: ../app/
    command: bash -c 'while !</dev/tcp/db/${POSTGRES_PORT}; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    restart: always
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 8001:8000


volumes:
  static_value:
  postgres_data:
